// ----------------------------------------------------------------------------
// Error code. 모든 에러관련 정의.
// 1~ 100000  critical error. 10000~20000 non critical error.
// ----------------------------------------------------------------------------

export enum GErrorCode {
  OK = 0, // OK

  // critical error.
  UNKNOWN_PACKET_TYPE = 1,

  // non critical error.
  // System
  NON_FATAL_ERROR_MARK = 1000,
  INTERNAL_ERROR,
  INVALID_REQ_BODY_PARAMETER,
  CLIENT_NOT_FOUND,

  // Auth
  INVAILD_ACCESS_TOKEN = 10000,
  INVAILD_CLIENT_TOKEN,
  DUPLICATE_LOGIN,
  ALREADY_LOGOUT,
  UNAUTHORIZED_NOT_LOGGED_IN,
  AUTH_INVALID_ACCOUNT_ID,
  AUTH_LOGIN_ERROR,
  AUTH_ENTER_WORLD_ERROR,
  AUTH_API_LOGOUT_ERROR,
  // db query
  AUTH_ACCOUNT_CREATE_QUERY_ERROR,
  AUTH_ACCOUNT_LOAD_QUERY_ERROR,
  AUTH_ACCOUNT_UPDATE_IS_ONLINE_QUERY_ERROR,
  AUTH_ACCOUNT_UPDATE_IS_ONLINE_AND_LAST_LOGIN_TIME_UTC_QUERY_ERROR,
  AUTH_ACCOUNT_UPDATE_SERVER_GROUP_ID_AND_LAST_WORLD_QUERY_ERROR,
  AUTH_ACCOUNT_UPDATE_LOGIN_PLATFORM_CLIENT_VERSION_QUERY_ERROR,
  AUTH_ACCOUNT_UPDATE_REVOKE_TIME_UTC_QUERY_ERROR,
  AUTH_PUB_ID_CREATE_QUERY_ERROR,
  AUTH_PUB_ID_LOAD_QUERY_ERROR,
  AUTH_WORLD_USER_LOAD_USER_ID_QUERY_ERROR,
  AUTH_WORLD_USERS_LOAD_QUERY_ERROR,

  // db txn
  AUTH_LOGIN_TXN_ERROR,
  AUTH_ENTER_WORLD_TXN_ERROR,

  // User
  // db query
  USER_LOAD_ID_QUERY_ERROR = 11000,
  USER_CREATE_QUERY_ERROR,
  USER_LOAD_QUERY_ERROR,
  USER_LOAD_ID_BY_ACCOUNT_ID_QUERY_ERROR,
  CHARACTER_UPDATE_QUERY_ERROR,
  USER_LOAD_CHARACTER_QUERY_ERROR,
  USER_LOAD_AVATAR_SLOTS_QUERY_ERROR,
  USER_RESET_AVATAR_SLOTS_QUERY_ERROR,
  USER_UPDATE_AVATAR_SLOTS_QUERY_ERROR,

  // db txn
  ENTER_CHARACTER_TXN_ERROR,
  CHANGE_AVATAR_SLOT_TXN_ERROR,
  ENTER_WORLD_TXN_ERROR,
  INIT_DEFAULT_USER_DATA_INIT_TXN_ERROR,
  INVENTORY_STORE_ITEMS_TXN_ERROR,

  // logic
  // common
  USER_API_ENTER_CHARACTER_SERVER_ERROR = 12000,
  CANNOT_FIND_ACCOUNT_ID,
  ALREADY_EQUIPPED_AVATAR_EQUIPEMENT,
  FAILED_TO_FETCH_WORLD,

  // world
  INVALID_WORLD = 13000,

  // field object
  FIELD_OBJECT_SET_FAILED = 13100,
  FIELD_OBJECT_SET_FAILED_INVALID_ITEM,
  FIELD_OBJECT_SET_FAILED_REMOVE_ITEM_FAIL,
  FIELD_OBJECT_SET_FAILED_ALREADY_ALLOCATED_POSITION,
  FIELD_OBJECT_SET_FAILED_INVALID_TILE,
  FIELD_OBJECT_SET_FAILED_BY_DB,
  FIELD_OBJECT_REMOVE_FAILED,
  FIELD_OBJECT_REMOVE_FAILED_INVALID_OBJECT,
  FIELD_OBJECT_REMOVE_FAILED_BY_DB,
  FIELD_OBJECT_UPDATE_FAILED,
  FIELD_OBJECT_UPDATE_FAILED_INVALID_OBJECT,
  FIELD_OBJECT_UPDATE_FAILED_BY_DB,
  FIELD_OBJECT_LOAD_FAILED_BY_DB,

  // item object
  ITEM_OBJECT_DROP_FAILED_INVALID_ITEM = 13200,
  ITEM_OBJECT_DROP_FAILED_CANT_DROP_POSITION,
  ITEM_OBJECT_DROP_FAILED_REMOVE_ITEM,
  ITME_OBJECT_DROP_FAILED_CREATE_OBJECT,
  ITEM_OBJECT_TAKE_FAILED_INVALID_ITEM,
  ITEM_OBJECT_TAKE_FAILED_ADD_ITEM_TO_INVENTORY,
  ITEM_OBJECT_TAKE_FAILED_OVER_TAKE_DISTANCE,

  // Items
  // World Inventory Interaction Error
  ITEM_INVALID_ITEM_GUID = 14000,
  ITEM_INVALID_ITEM_CMSID,

  INVALID_ITEM_COUNT,
  INVALID_ITEM_REMOVE_EQUIPPED_ITEM,
  INVALID_ITEM_REMOVE_ITEM_NOT_REMOVABLE,

  INVALID_REMOVE_ITEM_COUNT,
  WORLD_INVENTORY_CAPACITY_FULL,
  WORLD_INVENTORY_ITEM_GUID_DOES_NOT_EXIST,
  WORLD_INVENTORY_LOAD_ERROR,
  BAG_CAPACITY_FULL,
  BAG_ITEM_GUID_DOES_NOT_EXIST,
  BAG_LOAD_ERROR,
  AVATAR_INVENTORY_CAPACITY_FULL,
  AVATAR_INVENTORY_ITEM_GUID_DOES_NOT_EXIST,
  AVATAR_INVENTORY_LOAD_ERROR,
  ITEM_PROPERTY_NOT_CONSISTENT,
  // db query
  ITEM_LOAD_ALL_QUERY_ERROR,
  ITEM_LOAD_BY_ITEM_TYPE_QUERY_ERROR,
  ITEM_DELETE_QUERY_ERROR,
  ITEM_UPDATE_ALL_ATTRIBUTES_QUERY_ERROR,
  ITEM_UPDATE_COUNT_QUERY_ERROR,
  ITEM_INSERT_QUERY_ERROR,
  EQUIPMENT_SLOT_LOAD_QUERY_ERROR,
  EQUIPMENT_SLOT_UPDATE_QUERY_ERROR,
  EQUIPMENT_SLOT_RESET_QUERY_ERROR,

  INVAILD_CMS_TABLE = 20000,
  INVAILD_CMS_TABLE_ID,

  // Dedicated Server Instance
  NO_AVAILABLE_DEDICATED_SERVER = 30000,

  // 컨텐츠별로 소켓 로직 (메세지) 에러 정의
}
